import MedicineBatch from "../models/MedicineBatch.js";

/**
 * Get deduction plan without modifying database
 * @param {String} medicineId - ID of the medicine being sold
 * @param {Number} quantity - total quantity to deduct
 * @param {String} medicalStoreId - store context
 * @returns {Array} - plan containing batches and deduction quantities
 */
export const getFifoDeductionPlan = async (medicineId, quantity, medicalStoreId) => {
  const batches = await MedicineBatch.find({
    medicineId,
    medicalStoreId,
    quantityRemaining: { $gt: 0 },
  }).sort({ expiryDate: 1, receivedAt: 1 });

  let remainingToDeduct = quantity;
  const plan = [];

  for (const batch of batches) {
    if (remainingToDeduct <= 0) break;

    const deductQty = Math.min(batch.quantityRemaining, remainingToDeduct);
    plan.push({ batch, deductQty });
    remainingToDeduct -= deductQty;
  }

  if (remainingToDeduct > 0) {
    throw new Error(
      `Insufficient stock for medicine ${medicineId}. ${remainingToDeduct} units could not be fulfilled.`
    );
  }

  return plan;
};

/**
 * Execute a deduction plan
 * @param {Array} plan - the plan generated by getFifoDeductionPlan
 * @returns {Array} - list of batches updated with quantity deducted
 */
export const executeFifoDeductionPlan = async (plan) => {
  const updatedBatches = [];
  for (const { batch, deductQty } of plan) {
    batch.quantitySold += deductQty;
    batch.quantityRemaining -= deductQty;
    await batch.save();
    updatedBatches.push({ 
      batchId: batch._id, 
      quantityDeducted: deductQty,
      purchasePricePerUnit: batch.purchasePrice 
    });
  }
  return updatedBatches;
};

/**
 * Legacy wrapper: Deduct quantity from batches using FIFO logic immediately
 */
export const deductStockFIFO = async (medicineId, quantity, medicalStoreId) => {
  const plan = await getFifoDeductionPlan(medicineId, quantity, medicalStoreId);
  return await executeFifoDeductionPlan(plan);
};
